### PR TITLE
exclude-capi-and-dex-pods

### PR DESCRIPTION
**Pull request by calvix**
towards https://github.com/giantswarm/roadmap/issues/1705

background: capi controllers like capi bootstrap or capi controlplane are connecting to the WC cluster k8s APIs and should not use the proxy for such connections, CAPI itself should not need  connect to outside internet so it does not need proxy

CAPI using a proxy  is an issue when the customer has a restrictive proxy and only allows a predefined list of URLs and its impossible to add each API server  URL to domain list when cluster is created

`dex-k8s` authenticator pods are connecting to the dex ingress and again this should not go thru proxy

### CODE REVIEW

**Review by AverageMarcus — APPROVED** [review]
LGTM but can you correct the PR title please :)

**Comment by calvix** [comment]
> LGTM but can you correct the PR title please :)

fixed

**Comment by primeroz** [comment]
quick question , should we include "CAPA" and "CAPZ" controller manager in this exclusion ?

**Comment by calvix** [comment]
> ~quick question , should we include "CAPA" and "CAPZ" controller manager in this exclusion ?~
> 
> Stupid quesiton since they need to talk to the Cloud providers endpoints.

Yeah exactly, they need to talk to cloud provider so they need PROXY

**Pull request merged**
